receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  prometheus:
    config:
      scrape_configs:
        - job_name: "projeto-sd"
          static_configs:
            - targets: [ "0.0.0.0:8888" ]

processors:
  # batch metrics before sending to reduce API usage
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "otel-collector"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]
