global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'projeto-sd'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['projeto-sd-1:8080']
        labels:
          instance: 'projeto-sd-1'
      - targets: [ 'projeto-sd-2:8080' ]
        labels:
          instance: 'projeto-sd-2'
      - targets: [ 'projeto-sd-3:8080' ]
        labels:
          instance: 'projeto-sd-3'